### ISSUE TITLE
Break time goes first, instead of work time

### ISSUE THREAD

**Issue by rumboogy** [rumboogy/pomodoro-planner#9]
When the timer is started, the break time cycle runs first, then it goes into a work cycle. I think it's an issue with the logic statements in the `mainloop.init()` function in the `timer.js` file.

**Comment by star1954** [comment]
I believe that setting the first countdown time in
`var countdown = 300;`

to 0 may fix the bug. I'll test it as soon as I get the nodejs stuff 
On another note, you may want to remove the line
`timer.innerHTML = "Count down is done!";`

as we don't really need that anymore.
